spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: todo


  config:
    import: optional:configserver:http://localhost:8888

