
spring:
  application:
    name: outcome

  datasource:
      url: jdbc:mysql://localhost:3306/transaction
      username: root
      password:
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true




  config:
    import: optional:configserver:http://localhost:8888

