security:
  jwt:
    secret-key: 7638792F423F4428472B4B6250655368566D597133743677397A244326462948404D635166546A576E5A7234753778214125442A472D4B6150645267556B5870

springdoc.default-produces-media-type: application/json
spring:
  application:
    name: authentification
  datasource:
    url: jdbc:mysql://localhost:3306/integration
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  config:
    import: optional:configserver:http://localhost:8888
